/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTransaction: typeof import('./src/components/AddTransaction.vue')['default']
    Balance: typeof import('./src/components/Balance.vue')['default']
    Expense: typeof import('./src/components/Expense.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionList: typeof import('./src/components/TransactionList.vue')['default']
  }
}
